### ISSUE TITLE
Annotation Processor is not getting trigger on time

### ISSUE THREAD

**Issue by patricioe** [auntyellow/compiler-eclipse#1]
Hi, after switching to use this compiler plugin due to running into the OpenJDK issue [1], I'm running into another problem. I'm using AutoValue (https://github.com/google/auto) which uses the Java Annotation Processor, but with this compiler it seem like the annotations are not being process at all. See the error:

```
AutoValue_Person cannot be resolved to a type
```

and the code looks like this:

```
@JsonDeserialize(builder = AutoValue_Person.Builder.class)
@AutoValue
public abstract class Person {
```

Any ideas on how to get around this issue?

[1]

```
An exception has occurred in the compiler (1.8.0_25). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.IllegalStateException: endPosTable already set
    at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
    at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:350)
    at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:667)
    at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:892)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
```

**Comment by auntyellow** [comment]
This project is will be closed due to Java 1.8 support by plexus-compiler-eclipse 2.5 .
You may try to change your pom.xml with:

```
<build>
    <plugins>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.2</version>
            <configuration>
                <compilerId>eclipse</compilerId>
                <optimize>true</optimize>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.codehaus.plexus</groupId>
                    <artifactId>plexus-compiler-eclipse</artifactId>
                    <version>2.5</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
```

**Comment by patricioe** [comment]
I'm afraid I don't follow. You have already java 8, but an older version. I highly recommend to upgrade the supported version to the newer and more stable.

I followed your recommendation and my project still doesn't compile. In fact, Google/Autovalue fails left and right now. It seems like the AnnotationProcessor doesn't even kick in.

**Comment by patricioe** [comment]
I get this:

`[ERROR] /Users/patricioe/testapp/main/dtos/src/main/java/dtos/Test.java:[26] AutoValue_Test cannot be resolved to a type`

This indicates that the class is `AutoValue_Test` is not being create by the annotation processor.
